import React from 'react';
import RoleWorkspace from '../components/RoleWorkspace';

const CloseProfessionalSupportPage: React.FC = () => {
  return (
    <RoleWorkspace 
      allowedRoles={[
        'Acquisition Specialist',
        'Disposition Agent',
        'Title Agent',
        'Escrow Officer',
        'Notary Public',
        'Residential Appraiser',
        'Commercial Appraiser',
        'Home Inspector',
        'Commercial Inspector',
        'Energy Inspector',
        'Land Surveyor',
        'Insurance Agent',
        'Title Insurance Agent',
        'Mortgage Broker',
        'Mortgage Lender',
        'Loan Officer',
        'Mortgage Underwriter',
        'Hard Money Lender',
        'Private Lender',
        'Limited Partner (LP)',
        'Banking Advisor',
        'Seller Finance Purchase Specialist',
        'Subject To Existing Mortgage Purchase Specialist',
        'Trust Acquisition Specialist',
        'Hybrid Purchase Specialist',
        'Lease Option Specialist',
        'General Contractor',
        'Electrical Contractor',
        'Plumbing Contractor',
        'HVAC Contractor',
        'Roofing Contractor',
        'Painting Contractor',
        'Landscaping Contractor',
        'Flooring Contractor',
        'Kitchen Contractor',
        'Bathroom Contractor',
        'Interior Designer',
        'Architect',
        'Landscape Architect',
        'Kitchen Designer',
        'Bathroom Designer',
        'Lighting Designer',
        'Furniture Designer',
        'Color Consultant',
        'Permit Expeditor',
        'Energy Consultant',
        'Property Manager',
        'Long-term Rental Property Manager',
        'Short-term Rental Property Manager',
        'STR Setup & Manager',
        'Housekeeper',
        'Landscape Cleaner',
        'Turnover Specialist',
        'Handyman',
        'Landscaper',
        'Arborist',
        'Tenant Screening Agent',
        'Leasing Agent',
        'Bookkeeper',
        'Certified Public Accountant (CPA)',
        'Accountant',
        'Photographer',
        'Videographer',
        'AR/VR Developer',
        'Digital Twins Developer',
        'Estate Planning Attorney',
        '1031 Exchange Intermediary',
        'Entity Formation Service Provider',
        'Escrow Service Provider',
        'Legal Notary Service Provider',
        'Real Estate Consultant',
        'Real Estate Educator',
        'Financial Advisor',
        'Tax Advisor',
        'Relocation Specialist',
        'Real Estate Investment Advisor',
        'Real Estate Agent',
        'Real Estate Broker',
        'Realtor',
        "Buyer's Agent",
        'Listing Agent',
        'Commercial Agent',
        'Luxury Agent',
        'New Construction Agent',
        'Wholesaler',
        'Investment Advisor'
      ]}
      redirectPath="/close"
    />
  );
};

export default CloseProfessionalSupportPage;